SELECT '/home/grep/src/' || F.BOARD_ID || '/'|| F.FILE_ID  || F.FILE_NAME || F.FILE_EXT AS FILE_PATH 
FROM (SELECT * FROM (
        SELECT B.BOARD_ID AS MOST_VIEWED_BOARD, MAX(B.VIEWS) AS MAX_VIEW 
        FROM USED_GOODS_BOARD B JOIN USED_GOODS_FILE F
        ON B.BOARD_ID = F.BOARD_ID
        GROUP BY B.BOARD_ID
        ORDER BY MAX_VIEW DESC
    )
    FETCH FIRST 1 ROW ONLY
) M JOIN USED_GOODS_FILE F
ON M.MOST_VIEWED_BOARD = F.BOARD_ID
ORDER BY F.FILE_ID DESC


